# Generated by Django 5.1.1 on 2024-09-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apihome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcateogry',
            name='Cateogry',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcateogry',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='storage',
        ),
        migrations.DeleteModel(
            name='Cateogry',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Subcateogry',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='Product_variant',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
