# Generated by Django 5.1.1 on 2024-10-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Othervalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.PositiveIntegerField()),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.other')),
            ],
        ),
    ]
