# Generated by Django 5.1.1 on 2024-10-08 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_othervalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.othervalue')),
            ],
        ),
    ]
